# Generated by Django 4.2.4 on 2023-09-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_of_payment',), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
